name: "Build"
on: [push, pull_request]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "yarn"
        run: yarn --frozen-lockfile

      - name: "grunt"
        run: grunt

      - name: "Download and setup tests"
        id: setup-tests
        uses: "./.github/actions/action-thunderbird-tests"
        with:
          actions: download, setup
          channel: nightly
          xpcshellTestPaths: comm/calendar/test/unit/xpcshell-libical.ini, comm/calendar/test/unit/xpcshell-icaljs.ini

      - name: "Inject ical.js"
        run: |
          set -e
          cd $TBTESTS_RES_PATH/extensions/
          unzip \{e2fda1a4-762b-4020-b5ad-a41df1933103\}.xpi modules/ical.js
          diff -u modules/ical.js $GITHUB_WORKSPACE/build/ical.js
          sed "/-- start ical.js --/r $GITHUB_WORKSPACE/build/ical.js" modules/ical.js > modules/ical.js~
          mv modules/ical.js~ modules/ical.js
          zip -f \{e2fda1a4-762b-4020-b5ad-a41df1933103\}.xpi modules/ical.js
          rm -r modules

      - name: "Run Tests"
        uses: "./.github/actions/action-thunderbird-tests"
        with:
          actions: run
          channel: nightly
          xpcshellTestPaths: comm/calendar/test/unit/xpcshell-libical.ini, comm/calendar/test/unit/xpcshell-icaljs.ini
